name: Atualizar Relatório de Testes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Rodar testes
      run: |
        echo "## Resultados dos Testes" >> documentacao.md
        echo "- Teste 1: [x] Passou" >> documentacao.md
        echo "- Teste 2: [ ] Falhou" >> documentacao.md
        echo "- Teste 3: [x] Passou" >> documentacao.md

    - name: Commit e Push da documentação
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add documentacao.md
        git commit -m "Atualizando relatório de testes"
        git push
